community:
    githubFeeds:
        - https://github.com/ppi/framework/commits/2.1.atom
        - https://github.com/ppi/skeletonapp/commits/2.1.atom
        - https://github.com/ppi/website/commits/master.atom

    twitterUsername: ppi_framework

docs:
    pages:
        - index
        - getting_started
        - application
        - controllers
        - modules
        - routing
        - templating

oauth:
